max_width = 120
#use_small_heuristics = "Default"
fn_args_layout = "Compressed"
fn_call_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80
single_line_if_else_max_width = 120
short_array_element_width_threshold = 16
